"""add_tab_switch_count_to_interviews

Revision ID: 157a44e8f90c
Revises: 80d8179e5c33
Create Date: 2026-03-14 13:13:08.911283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157a44e8f90c'
down_revision: Union[str, None] = '80d8179e5c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # Add column as nullable first, then update existing rows, then make NOT NULL
    op.add_column('interviews', sa.Column('tab_switch_count', sa.Integer(), nullable=True))
    op.execute("UPDATE interviews SET tab_switch_count = 0 WHERE tab_switch_count IS NULL")
    op.alter_column('interviews', 'tab_switch_count', nullable=False)
    op.drop_column('interviews', 'multi_face_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('multi_face_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('interviews', 'tab_switch_count')
    op.drop_column('idempotency_keys', 'expires_at')
    # ### end Alembic commands ###
