"""add_departments_and_question_banks

Revision ID: 1b9727c11fff
Revises: 
Create Date: 2026-03-09 23:01:27.796122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9727c11fff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('department_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_interviews_department_id'), 'interviews', ['department_id'], unique=False)
    op.create_foreign_key(None, 'interviews', 'departments', ['department_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_department_id'), table_name='interviews')
    op.drop_column('interviews', 'department_id')
    # ### end Alembic commands ###
