"""add_human_evaluator_score_column

Revision ID: 2b8a26f047a3
Revises: 5e0a151f8833
Create Date: 2026-03-16 00:12:37.693902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8a26f047a3'
down_revision: Union[str, None] = '5e0a151f8833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('human_evaluator_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'human_evaluator_score')
    # ### end Alembic commands ###
