"""add_human_evaluator_feedback

Revision ID: 5e0a151f8833
Revises: 6feacf5c96f4
Create Date: 2026-03-15 23:38:30.062954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0a151f8833'
down_revision: Union[str, None] = '6feacf5c96f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_evaluator_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('evaluator_id', sa.String(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_evaluator_feedback_interview_id'), 'human_evaluator_feedback', ['interview_id'], unique=False)
    op.add_column('interviews', sa.Column('ai_paused_by', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'ai_paused_by')
    op.drop_index(op.f('ix_human_evaluator_feedback_interview_id'), table_name='human_evaluator_feedback')
    op.drop_table('human_evaluator_feedback')
    # ### end Alembic commands ###
