"""add_departments_and_question_banks_v2

Revision ID: 9a73123a929f
Revises: 1b9727c11fff
Create Date: 2026-03-09 23:16:09.048630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a73123a929f'
down_revision: Union[str, None] = '1b9727c11fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
